language: python
sudo: false

python:
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36

matrix:
  exclude:
    - python: 3.6
      env: TOXENV=py34
    - python: 3.6
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=py36

  last_finish: true

install:
  - pip install tox codacy-coverage -U pip

script:
  - tox -e $TOXENV -- --with-coverage --cover-package=pyplanet --cover-xml --cover-xml-file=coverage.xml

#after_success:
#  - python-codacy-coverage -r coverage.xml
