coverage:
  precision: 2
  round: down
  range: 40...60

  status:
    project:
      default:
        enabled: no
    patch:
      default:
        enabled: no
    changes:
      default:
        enabled: yes
